name: look for local overrides

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  list-overrides:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: List local files and diff them
        run: |
          find $GITHUB_WORKSPACE/local -type f | while read localfile ; do
            echo "******** File $localfile is not in the default directory!"
            diff -nwu ${localfile/local/default} ${localfile}
          done
