name: Pull pack from Stream instance
on: 
  workflow_dispatch:
    inputs:
      CRIBL_API_URL:
        description: Cribl API base url
        required: true
      CRIBL_USER:
        description: Username for API authentication
      CRIBL_PASSWORD:
        description: Password for API authentication
      CRIBL_TOKEN:
        description: Pre-authenticated (Bearer) Token for API
        
jobs:
  fetch-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current version
        uses: actions/checkout@v3

      - run: |
          echo "Extracting pack modifications for ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
          ./scripts/pull-pack.sh ${CRIBL_API_URL}
          
      - name: Commit and send changes to repository
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: Import automation
          default_author: github_actor
          message: "Workflow import by ${{ github.job }} init by ${{github.triggering_actor}}"
          new_branch: "pull-pack-${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
          push: true
